/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.exceptions;

public class App {
    double length = 0;

    public static void main(String[] args) {
        App app = new App();

        try {
            app.f0();
        }catch(ArithmeticException e){
            System.out.println("Nie udało się ustawić długości: "+e.getMessage());
            e.printStackTrace();
            app.setDefaultLength();
        }finally{
            System.out.println("Długość wynosi: "+app.length);
        }
    }

    public void setDefaultLength(){
        this.length = 100;
    }

    void f0(){
        //Proszę zobaczyć jak wykląda informacja wyświetlona przez wyjątek
        f1();
    }

    void f1(){
        f2();
    }

    void f2(){
        f3();
    }

    void f3(){
        f4();
    }

    void f4(){
        setLength(-10);
    }

    public void setLength(double length){
        this.length = length;

        if(length<0)
            throw new ArithmeticException("Długość nie może być ujemna");

        System.out.println("Ustawiono długość: "+length);
    }
}
