/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.exceptions;

public class App {
    double length = 0;

    public static void main(String[] args) {
        App app = new App();

        try {
            app.setLength(-10);
            app.setLength(250);
        }catch(ArithmeticException e){
            System.out.println("Nie udało się ustawić długości: "+e.getMessage());

        }
    }

    public void setLength(double length){
        this.length = length;

        if(length<0)
            throw new ArithmeticException("Długość nie może być ujemna");

        if(length>200){

        }

        System.out.println("Ustawiono długość: "+length);
    }
}
