/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.javafx;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        Group group = new Group();
        Scene scene = new Scene(group, 512,512);

        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
