/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.dequearray;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayDeque;
import java.util.Calendar;
import java.util.Deque;

class ChatRecord {
    String text;
    String date;

    ChatRecord(String text){
        this.text = text;

        DateFormat dateFormat = new SimpleDateFormat("m:s");

        Calendar calendar = Calendar.getInstance();
        date = "Czas "+dateFormat.format(calendar.getTime());
    }

    @Override
    public String toString() {
        return "["+text+"  "+date+"]"+"\n";
    }
}

public class App {
    Deque<chatRecord> chatDeque = new ArrayDeque<>();

    public static void main(String[] args) {
        App app = new App();
        app.chatTest();
    }

    public void chatTest(){

        chatDeque.offerLast(new ChatRecord("Pierwsza linia"));
        chatDeque.offerLast(new ChatRecord("Kolejna linia "));
        chatDeque.offerLast(new ChatRecord("Linia"));
        chatDeque.offerLast(new ChatRecord("Linia"));

        System.out.println(chatDeque);

    }
}
