/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.enum1.example;

public class App {

    public static void main(String[] args) {
        App app = new App();
    }
}
