/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.enum1.example;

enum Planet{
    MERCURY,
    EARTH,
    MARS,
    VENUS,
    JUPITER
}

public class App {

    public static void main(String[] args) {
        App app = new App();
        //app.example1();
        app.example2();
    }

    void example1(){

        for(Planet planet : Planet.values()){
            System.out.println(planet);
        }

        Planet planete = Planet.JUPITER;

        switch(planete){
            case EARTH:
            case MARS:
                System.out.println("Można wysłać pojazd badawczy");
                break;
            case JUPITER:
                System.out.println("Gazowy olbrzym");
                break;
            default:
                System.out.println("Inna planeta");
        }

    }

    void example2(){
        for(Students student : Students.values())
            System.out.println(student.info());

        Students student = Students.KRZYSZTOF_ZAREBSKI;
        System.out.println(student.getHeight());

        switch(student){
            case KRZYSZTOF_ZAREBSKI:
            case KAMIL_STASICA:
                System.out.println("Krzysztof Zarębski");
                break;
            case KATARZYNA_SKRZYP:
                System.out.println("Krzysztof Zarębski");
            default:
                System.out.println("Wybrano innego studenta...");
                break;
        }

        System.out.println("Informacje o grupie: "+Students.groupInfo);
    }
}
