/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.enum1.example;

import java.util.ArrayList;

enum Planet{
    MERCURY,
    EARTH,
    MARS,
    VENUS,
    JUPITER
}

public class App {

    public static void main(String[] args) {
        App app = new App();
        app.example1();
    }

    void example1(){

        for(Planet planet : Planet.values()){
            System.out.println(planet);
        }

        Planet planete = Planet.JUPITER;

        switch(planete){
            case EARTH:
            case MARS:
                System.out.println("Można wysłać pojazd badawczy");
                break;
            case JUPITER:
                System.out.println("Gazowy olbrzym");
                break;
            default:
                System.out.println("Inna planeta");
        }

        String text = "Jakiś napis";



    }
}
