/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.generics.example;

import java.util.ArrayDeque;
import java.util.Deque;

class Chat<T>{
    Deque<T> chatDeque = new ArrayDeque<>();

    void addLine(T line){
        chatDeque.add(line);
    }

    void printChat(){
        System.out.println(chatDeque);
    }

}

public class App {
    public static void main(String[] args) {
        App app = new App();
        app.example1();
    }

    public void example1(){
        Chat<String> chat = new Chat<>();
        chat.addLine("Pierwsza linia");
        chat.addLine("Kolejna linia");

        chat.printChat();
    }
}
