/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.generics.example;

public class App {
    public static void main(String[] args) {
        App app = new App();
        app.example1();
    }

    public void example1(){

    }
}
