/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.deque;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.NoSuchElementException;

class Student{
    final String name;
    final String surname;

    private static int no = 0;
    final Integer id;

    Student(String name, String surname){
        this.name = name;
        this.surname = surname;
        no++;
        id = no;
    }

    @Override
    public String toString() {
        return "Student{" +
                "name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", id=" + id +
                '}';
    }
}

public class App {

    Deque<Double> deque = new ArrayDeque<>();
    Deque<Student> studentsDeque = new ArrayDeque<>();

    public static void main(String[] args) {
        App app = new App();
        //app.dequeTest();
        app.dequeTest1();

        //app.dequeStudent();
    }

    public void dequeTest(){
        for(int i=0;i<10;i++)
            deque.offerFirst((double)i);

        System.out.println(deque);

        deque.offerFirst(100.0);
        deque.offerLast(200.0);

        System.out.println(deque);
        System.out.println("First element: "+deque.peekFirst());
        System.out.println(deque);
        System.out.println("Last element: "+deque.peekLast());
        System.out.println(deque);
        System.out.println("First element: "+deque.pollFirst());
        System.out.println(deque);
        System.out.println("Last element: "+deque.pollLast());
        System.out.println(deque);
    }

    public void dequeTest1(){
        for(int i=0;i<10;i++)
            deque.addFirst((double)i);

        System.out.println(deque);

        for(int i=0;i<20;i++) {
            //if(!deque.isEmpty()) {
            try {
                deque.removeFirst();
                System.out.println(deque);
            }catch(NoSuchElementException e){
                System.out.println("Przechwycono wyjątek...");
                e.printStackTrace();
            }finally {
                System.out.println("Ta linia zawsze się wykona");
            }
            //}
        }
    }

    public void dequeStudent(){
        for(int i=0;i<10;i++)
            studentsDeque.offerFirst(new Student("Przemysław","Stokłosa"));

        System.out.println(studentsDeque);
    }

    //ćwiczenie 1 - proszę wykonać samodzielnie
    public void function0(int no){

    }
}
