/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.deque;

import java.util.ArrayDeque;
import java.util.Deque;

public class App {

    Deque<Double> deque = new ArrayDeque<>();

    public static void main(String[] args) {
        App app = new App();
        app.dequeTest();
    }

    public void dequeTest(){

    }
}
