/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.deque;

import java.util.ArrayDeque;
import java.util.Deque;

public class App {

    Deque<Double> deque = new ArrayDeque<>();

    public static void main(String[] args) {
        App app = new App();
        app.dequeTest();
    }

    public void dequeTest(){
        for(int i=0;i<10;i++)
            deque.offerFirst((double)i);

        System.out.println(deque);

        deque.offerFirst(100.0);
        deque.offerLast(200.0);

        System.out.println(deque);
        System.out.println("First element: "+deque.peekFirst());
        System.out.println(deque);
        System.out.println("Last element: "+deque.peekLast());
        System.out.println(deque);
        System.out.println("First element: "+deque.pollFirst());
        System.out.println(deque);
        System.out.println("Last element: "+deque.pollLast());
        System.out.println(deque);
    }
}
