/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javafx.example;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.stage.Stage;

import java.util.ArrayList;

public class App extends Application {
    ArrayList<Figure> figures = new ArrayList<>();
    ArrayList<Figure> figuresToDraw = new ArrayList<>();

    @Override
    public void start(Stage primaryStage) throws Exception {
        Group group = new Group();
        Scene scene = new Scene(group, 512, 512);

        Button generate = createButton("Generate");
        Button clear = createButton("Clear");
        Button arrayList = createButton("All");
        Button set = createButton("Set");

        generate.setOnMouseClicked(e->{
            generate();
        });

        arrayList.setOnMouseClicked(e->{
            drawArrayList(group);
            /*Circle circle = new Circle();
            circle.setRadius(50);
            circle.setCenterX(100);
            circle.setCenterY(100);
            group.getChildren().add(circle);*/
        });

        HBox hBox = new HBox();
        hBox.getChildren().addAll(generate,clear,arrayList,set);

        hBox.setPrefSize(scene.getWidth(),scene.getHeight());
        hBox.setAlignment(Pos.BOTTOM_CENTER);
        //hBox.setSpacing(5);

        group.getChildren().add(hBox);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    void generate(){
        for(int i=0;i<10;i++){
            Color c1 = Color.color(Math.random(),Math.random(),Math.random());
            Figure figure = new Figure(c1);
            figures.add(figure);
        }
    }

    void drawArrayList(Group group){
        figuresToDraw.removeAll(figuresToDraw);
        figuresToDraw.addAll(figures);

        for(Figure figure: figuresToDraw)
            group.getChildren().remove(figure.getShape());

        figuresToDraw.forEach(figure->figure.draw(group));
    }

    Button createButton(String text){
        //W tej funkcji można ustawić parametry wszystkich klawiszy
        Button button = new Button(text);
        button.setMaxWidth(Double.MAX_VALUE);
        HBox.setHgrow(button, Priority.ALWAYS);
        return button;
    }


}
