/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.exceptions;

class MyException extends RuntimeException{
    public MyException(String message) {
        super(message);
    }
}

public class App {
    double value;

    public static void main(String[] args) {
        App app = new App();

        try {
            app.setValue(-10);
        }catch(MyException e){
            e.printStackTrace();
        }
    }

    void setValue(double value){
        if(value<0)
            throw new MyException("Wartość nie może być ujemna");

        this.value = value;

        System.out.println("Ustawiam wartość: "+this.value);
    }
}
