/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.exceptions;

class MyException extends RuntimeException{
    private String info = null;

    public MyException(String message, double value) {
        super(message);
        info = "Funkcja próbuje ustawić wartość: "+value;
    }

    public String getInfo() {
        return info;
    }
}

public class App {
    double value;

    public static void main(String[] args) {
        App app = new App();

        try {
            app.setValue(-10);
        }catch(MyException e){
            System.out.println("Wyrzucono wyjątek: "+e.getMessage());
            System.out.println(e.getInfo());
            e.printStackTrace();

        }
    }

    void setValue(double value){
        if(value<0)
            throw new MyException("Wartość nie może być ujemna", value);

        this.value = value;

        System.out.println("Ustawiam wartość: "+this.value);
    }
}
