/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.exceptions;

class MyException extends Exception{
    private String info;

    public MyException(String message, double value) {
        super(message);
        info = "Funkcja próbuje ustawić wartość: "+value;
    }

    public String getInfo() {
        return info;
    }
}

public class App {
    double value;

    static double[] array = {1,2,3,4,5};

    public static void main(String[] args) {
        App app = new App();

        try {
            app.setValue(10);
        }catch(MyException e){
            System.out.println("Wyrzucono wyjątek: "+e.getMessage());
            System.out.println(e.getInfo());
            e.printStackTrace();

        }

        try {
            array[5] = 1;
        }catch(IndexOutOfBoundsException e){
            System.out.println("Nieprawidłowy indeks tablicy: "+e.getMessage());
            e.printStackTrace();
        }

        app.f1();

    }

    void f0() throws MyException{
        setValue(-50);
    }

    void f1() {
        try {
            f0();
        } catch (MyException e) {
            e.printStackTrace();
        }
    }

    void setValue(double value) throws MyException{
        if(value<0)
            throw new MyException("Wartość nie może być ujemna", value);

        this.value = value;

        System.out.println("Ustawiam wartość: "+this.value);
    }
}
